feat: add section id for methodology
radicallyopensecurity/pentext pull request #83
Opened 2021-06-24 09:34 UTC by PeterMosmans

Apply opinionated XML formatting

2021-07-18 07:58 UTC, skyanth requested changes
Pentestmethodologie, not Pentest methodologie
https://www.spatiegebruik.nl/regels.html#:~:text=Samenstellingen%20worden%20in%20het%20Nederlands,samengestelde%20woord%20is%20altijd%20fout.

2021-07-18 14:46 UTC, gronke requested changes

2021-07-18 14:46 UTC, gronke commented on xml/source/snippets/offerte/nl/methodology.xml
> +    /> gebruikt open-source scanning tools als basis, maar
There should be no line break here.

2021-07-18 14:46 UTC, gronke commented on xml/source/snippets/offerte/nl/methodology.xml
> +  >Stappen 4-6 kunnen meerdere malen herhaald worden per test. Zo kan er bijvoorbeeld door exploitatie van kwetsbaarheden toegang worden
Please remove the line break here as well.

2021-07-19 08:01 UTC, PeterMosmans commented
@skyanth @gronke :
I've fixed the spelling error (and another one :)), and applied opinionated Prettier formatting.

2021-07-19 14:45 UTC, merged